info:
    description: "Inventory Management Service"
spring:
  application:
    name: inventory-service
  data:
    mongodb:
        uri: mongodb://localhost:27017/OMS
#        database: OMS
security:
    basic:
      enabled: false
logging:
    level: error
#com.oms.inventory: debug
server:
    port: 9099
